---
title: "Covid"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

## Librerías:

```{r, message=FALSE, warning=FALSE}
library(curl)
library(tidyverse)
```

## Datos:

### Casos de Covid en el Perú
```{r, message=FALSE, warning=FALSE}
tmp <- tempfile()
curl_download("https://cloud.minsa.gob.pe/s/Y8w3wHsEdYQSZRp/download", tmp)
df <- read_csv(tmp) # En df la unidad muestral es un caso de COVID
```

---

### Datos de movilización en Perú
```{r, message=FALSE, warning=FALSE}
tmp <- tempfile()
curl_download("https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv", tmp)
read_csv(tmp, col_types = "ccccDdddddd") %>%
    filter(country_region_code == "PE") -> df_mov
```

---

### Cantidad de infectados y nuevas infecciones por día
```{r, message=FALSE, warning=FALSE}
df %>%
    group_by(FECHA_RESULTADO) %>%
    summarise(N = n()) %>%
    mutate(FECHA_RESULTADO = lubridate::dmy(FECHA_RESULTADO)) %>%
    arrange(FECHA_RESULTADO) %>%
    mutate(NSUM = cumsum(N)) -> df_infec
```

## Nuevos casos por día

```{r}
df_infec %>%
    filter(FECHA_RESULTADO >= "2020-04-10" & FECHA_RESULTADO <= "2020-04-30") %>%
    plot(N~FECHA_RESULTADO, data = .)
```

## Casos totales por día

```{r}
plot(df_infec$FECHA_RESULTADO, df_infec$NSUM)
```

## Movilización recreacional por día
```{r}
df_mov %>%
    group_by(date) %>%
    summarise(mov = mean(retail_and_recreation_percent_change_from_baseline, na.rm = TRUE)) %>%
    #filter(date >= "2020-04-10" & date ) %>%
    plot()
```
