name: R CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Cache R packages
      id: cache-r
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ runner.os }}-r-pkgs

    - uses: actions/checkout@v2

    - name: deps
      run: sudo apt-get install inkscape r-base pandoc

    - name: Makevars
      run: |
        mkdir ~/.R
        echo "MAKEFLAGS = -j2" > ~/.R/Makevars
        echo "CXXFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> ~/.R/Makevars
        echo "CFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> ~/.R/Makevars

    - name: rmarkdown
      run: sudo R -e "install.packages('rmarkdown', dependencies=TRUE, repos='http://cran.rstudio.com/')"

    - name: tidyverse
      run: sudo R -e "install.packages('tidyverse', dependencies=TRUE, repos='http://cran.rstudio.com/')"

    - name: build
      run: make install DESTDIR=dest -j$(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: proyecto
        path: dest/*
