name: R CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/2020-01-est-19/proyecto/arch-env:latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: make install DESTDIR=dest -j$(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: proyecto
        path: dest/*
