name: R CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1

    - name: deps
      run: sudo apt-get install inkscape

    - name: r deps
      run: sudo apt-get install
        r-cran-rmarkdown
        r-cran-tidyverse

    - name: build
      run: make
