name: R CI

on:
  schedule:
      # Touch cache or it will be deleted
      - cron: '0 0 */6 * *'

  push:
      branches: [ '*' ]
  pull_request:
      branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: renv-cache
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: deps
      run: sudo apt-get install r-base pandoc libcurl-dev

    - name: Makevars
      run: |
        echo "MAKEFLAGS = -j2" > Makevars
        echo "CXXFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> Makevars
        echo "CFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> Makevars
        mkdir ~/.R
        mv Makevars ~/.R

    - name: Make writeable
      run: |
        mkdir -p /usr/local/lib/R/site-library
        sudo chmod 777 /usr/local/lib/R/site-library

    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::consent(TRUE)
        renv::restore()

    - name: build
      run: make install DESTDIR=dest -j$(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: proyecto
        path: dest/*
