name: R CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: deps
      run: sudo apt-get install inkscape

    - name: r deps
      run: sudo apt-get install
        r-cran-rmarkdown
        r-cran-tidyverse

    - name: build
      run: |
          export MAKEFLAGS=-j$(nproc)
          make install DESTDIR=dest

    - uses: actions/upload-artifact@v2
      with:
        name: proyecto
        path: dest/*
