name: R CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/cache@v2
      id: renv-cache
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - uses: actions/checkout@v2

    - name: deps
      run: sudo apt-get install inkscape r-base pandoc libcurl4-gnutls-dev

    - name: Makevars
      run: |
        echo "MAKEFLAGS = -j2" > Makevars
        echo "CXXFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> Makevars
        echo "CFLAGS = -O3 -pipe -fno-plt -flto -fno-fat-lto-objects" >> Makevars
        mkdir ~/.R
        mv Makevars ~/.R

    - name: renv
      if: steps.renv-cache.outputs.cache-hit != 'true'
      run: sudo R -e "install.packages('renv', dependencies=TRUE, repos='http://cran.rstudio.com/')"

    - name: r packages
      run: ./renv.r

    - name: build
      run: make install DESTDIR=dest -j$(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: proyecto
        path: dest/*
